spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: notify
    password: notify!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
logging:
  level:
    org:
      springframework:
        security: debug

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-mils: 604800000  # 7 days